spring:
  application:
    name: service-another-micro-dude
  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
  sleuth:
    sampler:
      # percentage to traced requests
      # why? cuz we can't trace all cuz performance impact
      probability: 1.0

server:
  port: 8100


management:
  endpoints:
    web:
      exposure:
        include=*:

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s

  retry:
    instances:
      alo:
        maxAttempts: 5
        waitDuration: 2s
        enableRandomizedWait: true
        randomizedWaitFactor: 0.5
#eureka:
#  client:
#    service-url: