spring:
  application:
    name: service-another-micro-dude
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8100

management:
  endpoints:
    web:
      exposure:
        include=*:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s

  retry:
    instances:
      alo:
        maxAttempts: 5
        waitDuration: 2s
        enableRandomizedWait: true
        randomizedWaitFactor: 0.5