spring:
  application:
    name: service-micro-dude-kman
  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  port: 8200
