#  sleuth:
#    sampler:
#      probability: 1.0
spring:
  application:
    name: service-micro-dude-kman
management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  port: 8200
