spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/salah9abdelrahman/config-server-test

server:
  port: 8888


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"