spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/salah9abdelrahman/config-server-test


  application:
    name: config-server
#
#  sleuth:
#    sampler:
#      probability: 1.0

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: refresh
