spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/salah9abdelrahman/config-server-test
server:
  port: 8888

encrypt:
  key: marwan-pablo

