spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/salahabdelrahman/Desktop/projects/self/config-server-test


  application:
    name: config-server


server:
  port: 8888

